### ISSUE TITLE
Feature request: Pre-folded on loadup

### ISSUE THREAD

**Issue by ux-engineer** [leezng/vue-json-pretty#101]
Could there be an option for the JSON snippet to be pre-folded on loadup?

**Comment by leezng** [comment]
@ux-engineer  Do you mean the `deep` prop?

**Comment by ux-engineer** [comment]
@leezng I mean when the component loads up, it's showing `{ ... }`

**Comment by leezng** [comment]
Please use the `deep` prop.

**Comment by ux-engineer** [comment]
@leezng oh I noticed that prop by name, however, I failed to connect 'deep' name for this feature. Perhaps i.e. 'prefold' would be more descriptive name for this?

**Comment by ux-engineer** [comment]
Btw there's some lack in deep property's validation.

` [Vue warn]: Invalid prop: type check failed for prop "deep". Expected Number, got Boolean with value true.`
 
```vue
<!-- This works -->
<vue-json-pretty :data="debug" :deep="0" />

<!-- This doesnt-->
<vue-json-pretty :data="debug" deep />
```

First, property's default value should be 0. Then when you add the property to your custom component with shorthand without a value, you can use this:

My recommendation:

```vue
<!-- This doesnt -->
<vue-json-pretty :data="debug" prefold />
```
 
 This property validation object may work in this case:
 
```
prefold: {
  type: [Boolean, Number],
  required: false, // Accepts null and undefined as well
  default: undefined,
},
```

**Comment by leezng** [comment]
https://github.com/leezng/vue-json-pretty#props
The type of deep attribute is number, the default is Infinity.

**Comment by ux-engineer** [comment]
However this feature request was about another prop which would control if the root node is folded by adding `prefold` attribute to the element.

Now if I use just `deep` and give it 0, then when I'm clicking open the root node I need to click through all levels... Prefold would show immediately after first click all the defined depth levels.
