### ISSUE TITLE
support toJSON()

### ISSUE THREAD

**Issue by x12a1f** [leezng/vue-json-pretty#108]
Hi, I'm using vue 2 and I was wondering if it would be possible for vue-json-pretty to support the toJSON() method just like JSON.stringify() does?

I have some objects with circular dependencies. Those objects have a toJSON() method which removes the circular dependency so that JSON.stringify() can show them properly. 

However, since vue-json-pretty does not use toJSON() the objects with circular dependencies cause the browser to hang (and eventually give an error)

Thanks.

**Comment by leezng** [comment]
No, you can only use the interface defined by the component, and the data format needs to be processed by yourself.
