### ISSUE TITLE
Prop to set visibleCount number of lines in virtual mode

### ISSUE THREAD

**Issue by LukeFinch** [leezng/vue-json-pretty#109]
In virtual mode the number of lines defaults to 10.
It would be beneficial if I could change that number to be a custom value.

-- Unrelated issue.
I was trying to fork and build a PR for this, but ran into some eslint issues...

**Comment by leezng** [comment]
@LukeFinch 
Thanks.
Welcome to send a PR. I can help if you have any questions.

**Comment by LukeFinch** [comment]
HI @leezng managed to get ESlint working, but when installing node modules for this project, my package-lock changed dramatically. If you can advise how I can fix that, that would be great.

I will open a PR and link it to this issue. I updated the example file to show my changes.
