### ISSUE TITLE
Integrate with nuxt

### ISSUE THREAD

**Issue by bachdgvn** [leezng/vue-json-pretty#11]
I use vue-json-pretty with nuxtjs. But it dont work because "document is undefined".
Can you make a version for this integration?

**Comment by leezng** [comment]
Need time to develop.

**Comment by Kerita** [comment]
@bachdgvn You can use it like this in Nuxt.js.

By the  way, the project is awesome and cool. Thanks @leezng . And could you add the usage in Nuxt.js  to the document to help other people?

```
// ~/plugins/VueJSONPretty.js
import Vue from 'vue'
import VueJsonPretty from 'vue-json-pretty'

Vue.component('VueJsonPretty', VueJsonPretty)
```

```
// nuxt.config.js
// ssr: false means not render in server
plugins: [
  {
      src: '~plugins/VueJSONPretty',
      ssr: false,
  }
]
```

**Comment by pranav-xx** [comment]
@Kerita 
Event after adding above config, it still gives document is not defined on refresh. Am I missing something?

**Comment by rahulkumarsingh73690** [comment]
Can Anyone Tell me, Now is it support Nuxt or not?

**Comment by orangevinz** [comment]
> Can Anyone Tell me, Now is it support Nuxt or not?

I'm really new to nuxtjs (less than a week) but this way worked for me :
For sure some steps are not required but try something like

1. Write a file (VueJsonPretty.js) in plugins folder with
`
import Vue from 'vue'
import VueJsonPretty from 'vue-json-pretty'

Vue.use(VueJsonPretty)
`

2. In the nuxt.config.js
`
plugins: [
    { src: '~/plugins/VueJsonPretty.js', mode:  'client' },
  ],
`

3. Use the component

`
<no-ssr>
    <vue-json-pretty></vue-json*pretty>
</no-ssr>
`

4. Import your component
`
components: {
      VueJsonPretty: () =>
        process.client ? import('vue-json-pretty') : null,
    },
`

**Comment by leezng** [comment]
Does anyone have a successful experience on Nuxt, can you help add some project documents or demo?

**Comment by rchl** [comment]
In webpack 5 (or 4) it would be a matter of configuring `output.globalObject` option so that generated code doesn't use `document` or `window` but this project is still on webpack 3 so not sure how to fix it there.

A related issue in another project: https://github.com/JonWatkins/vue-runtime-template-compiler/issues/1

**Comment by bob-lee** [comment]
My project is using `nuxt@2.13.0` and `vue-json-pretty@1.6.3` without problem.

package.json
```
  "dependencies": {
...
    "vue-json-pretty": "^1.6.3",
```
index.vue:
```
<template>
...
  <vue-json-pretty />
</template>

<script>
import VueJsonPretty from 'vue-json-pretty'

export default {
  components: {
    VueJsonPretty,
  },
...
</script>

**Comment by leezng** [comment]
Updated to webpack4 on version 1.6.5.

**Comment by rchl** [comment]
Suggested fix: https://github.com/leezng/vue-json-pretty/pull/82

**Comment by rchl** [comment]
@bob-lee it probably works for you because you are running your project in SPA mode.

**Comment by bob-lee** [comment]
@rchl confirmed. my project is on spa mode.

**Comment by mreed19** [comment]
Just wanted to share that I was able to get this working on v1.6.7 with SSR by doing the following

1. In `plugins/vue-json-pretty.js`

```
import Vue from 'vue';
import VueJsonPretty from 'vue-json-pretty';

Vue.component('vue-json-pretty', VueJsonPretty);
```

2. In `nuxt.config.js`
```
plugins: [
  { src: '~/plugins/vue-json-pretty.js', mode: 'client' }
]
```

3. In some page (`index.vue`). No need to import or register component at this level as it was already globally registered above.
```
<template>
  <client-only>
    <vue-json-pretty
      ...
    />
  </client-only>
</template>

**Comment by rchl** [comment]
To be specific, that doesn't make it work with SSR. It makes the component not be included in server-rendered page.

So it makes it work in the sense that SSR doesn't crash, but not in the sense that the component is server-side-rendered.

**Comment by gilles6** [comment]
Nuxt3
`plugins/vue-json-pretty.ts`
```
import VueJsonPretty from "vue-json-pretty";

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.component("VueJsonPretty", VueJsonPretty);
});
```
