### ISSUE TITLE
error message:TypeError: (0 , o.defineComponent) is not a function

### ISSUE THREAD

**Issue by lqdahv** [leezng/vue-json-pretty#111]
![QQ截图20210306172556](https://user-images.githubusercontent.com/24808833/110205931-e15bc400-7eb5-11eb-934f-594442e2bafe.png)

How to solve it?😵😵😵

**Comment by lqdahv** [comment]
npm i vue-json-pretty@1.7.1 --save

**Comment by preethamsridhar** [comment]
Worked for me. Thanks a lot
