### ISSUE TITLE
Issue enabling scrolling knob

### ISSUE THREAD

**Issue by Matt-Texier** [leezng/vue-json-pretty#113]
Hi,

I am running vue-json-pretty in a vuejs project with the following release:
```
"vue-json-pretty": "^1.7.1",
```
I am trying to add a vue-json-pretty component into my component:
```
<template>
    <v-card>
        <v-card-title>
            <span class="text--h5" style="color:#6EC1E4">
                IP VPN Data and related models
            </span>
        </v-card-title>
        <v-card-subtitle>
            <span class="text--h5" style="color:#6EC1E4">
                According to IP VPN Model
            </span>
        </v-card-subtitle>
        <v-card-text>
            <vue-json-pretty
                :data="ipVpnServicesNested"
                :virtual="true"
            />
        </v-card-text>
    </v-card>
</template>
```
I have included both component file and css file as mentioned in the README.
```
import VueJsonPretty from 'vue-json-pretty';
import 'vue-json-pretty/lib/styles.css';

export default {
    name: "IpVpnDashboard.vue",
    components: {
        VueJsonPretty,
    },
``` 
I do have my JSON tree properly formatted however, there is no scrolling bar and as such I cannot display nor navigate into the whole JSON tree.

I tried many options without success.

Could you please help me to understand the problem  which is probably behind the keyboard :-) ?

**Comment by leezng** [comment]
The component itself will not have a scroll bar style, you must set the corresponding style on your container.
