### ISSUE TITLE
White space before commas

### ISSUE THREAD

**Issue by tobystokes** [leezng/vue-json-pretty#115]
(Firstly, thank you for this great component!)

I'm having an issue with white-space nodes between the values and the following `<span>,</span>` which causes the comma to wrap in certain situations where the space is limited:

![image](https://user-images.githubusercontent.com/109024/117298223-05fcf980-ae6f-11eb-9a93-a47997957346.png)

I can see that there is a white-space node being inserted here, but I'd suggest that as a default display that is probably not what is desired.

It is addable by css alone with e.g. `span:before { content: ' ' }` but I'm fairly sure there is no way to _remove_ it with css.

**Comment by leezng** [comment]
The problem cannot be reproduced, maybe it is affected by your project css.
