### ISSUE TITLE
Possible to use this from CDN?

### ISSUE THREAD

**Issue by dsottimano** [leezng/vue-json-pretty#123]
I'm using CDN implementation for Vue 3 and would like to include your component also using CDN (https://www.jsdelivr.com/package/npm/vue-json-pretty?version=2.0.2).

How might I do this?

**Comment by leezng** [comment]
Do you mean #2 ?

**Comment by dsottimano** [comment]
That worked, thank you - but I'd like to use Vue 3.  Please forgive me if I'm missing something obvious but this is just one implementation I've tried:

```
<!DOCTYPE html>

<head>
	<script src="https://unpkg.com/vue@3.0.2"></script>
	<script src="https://cdn.jsdelivr.net/npm/vue-json-pretty@2.0.2/lib/vue-json-pretty.min.js"></script>

</head>

<body>
	<div id="app">

		<vue-json-pretty :data="jsonData"></vue-json-pretty>

	</div>

	<script>
		const app = Vue.createApp({
			data() {
				return {
					jsonData: { "country": "Germany", "capital": "Berlin", "currency": "Euro" }
				}
			}
		})

		app.component('VueJsonPretty', VueJsonPretty.default)
		app.mount('#app')
	</script>

</body>

</html>
```

**Errors:**

```
vue-json-pretty.min.js:5 Uncaught TypeError: Cannot read property 'defineComponent' of undefined
    at Object.719 (vue-json-pretty.min.js:5)
    at o (vue-json-pretty.min.js:5)
    at vue-json-pretty.min.js:5
    at vue-json-pretty.min.js:5
    at vue-json-pretty.min.js:5
    at vue-json-pretty.min.js:5
719 @ vue-json-pretty.min.js:5
o @ vue-json-pretty.min.js:5
(anonymous) @ vue-json-pretty.min.js:5
(anonymous) @ vue-json-pretty.min.js:5
(anonymous) @ vue-json-pretty.min.js:5
(anonymous) @ vue-json-pretty.min.js:5
```

```
vuejson.html:25 Uncaught ReferenceError: VueJsonPretty is not defined
    at vuejson.html:25
(anonymous) @ vuejson.html:25
```

**Comment by leezng** [comment]
@dsottimano 
I found a bug here, the component reads the global `vue`, but vue3 is mounted with `window.Vue`, I will solve it in the next version, currently you can skip it by the following method:

```html
<script src="https://unpkg.com/vue@3.0.2"></script>
<script>window.vue = Vue</script>
<script src="https://cdn.jsdelivr.net/npm/vue-json-pretty@2.0.2/lib/vue-json-pretty.min.js"></script>
```

**Comment by dsottimano** [comment]
I would have never figured that out, thank you very much.   Would you like me to make a PR to update the readme with these 2 code snippets and a link to your [demo](https://leezng.github.io/vue-json-pretty/)  ?  I bet it would help quite a few people.  

Also, where can I add in feature requests?

**Comment by leezng** [comment]
Yeah, You can add a description in REDME, such as `Use CDN`.
