### ISSUE TITLE
Expand on root level expands all childs

### ISSUE THREAD

**Issue by NTTAKR** [leezng/vue-json-pretty#125]
I want to give the user a good option to get the overall structure of a JSON data item. 

I display only the level one nodes on the root. The rest is shown with showLength="true". 
As soon as the user clicks on any bracket ALL child nodes below that are recursively expanded. 
How can I change that behavior to only expand the next level on the node I clicked on?

**Comment by fredrivett** [comment]
I agree with this PR, have had a look at the codebase and submitted a couple PR's, one for the `1.x` branch (Vue 2) and one for the `dev` branch (Vue 3).

This is working locally for me, the simple change is to this line:

Vue 2: https://github.com/leezng/vue-json-pretty/blob/cc2e0f2c62997edb8a3ba1722b7ab46071ab4864/src/components/Tree/index.vue#L134
Vue 3: https://github.com/leezng/vue-json-pretty/blob/fd162d12e9bdea4008330d743206f1826cd1aaf7/src/components/Tree/index.tsx#L62

For both of these the diff to implement this (without the prop option used in the PR's):

```diff
-         item.level === this.deep
+         item.level >= this.deep
```

Hopefully the maintainers will agree and merge in my PR's but the above change will work if you want this functionality before that. I implemented it by copying the `src` to my project, updating the relative links and changing that line.
