### ISSUE TITLE
ts build时的报错和解决建议

### ISSUE THREAD

**Issue by Ljumo** [leezng/vue-json-pretty#128]
build时会提示
../../node_modules/vue-json-pretty/types/components/TreeNode/index.d.ts:2:39 - error TS2307: Cannot find module 'src/utils' or its corresponding type declarations.
后面查看了代码之后发现是/node_modules/vue-json-pretty/types/components/TreeNode/index.d.ts中 
import { JSONFlattenReturnType } from 'src/utils'报错，
这里的路径应该为'../../utils';
希望尽早修改

**Comment by leezng** [comment]
duplicate #121
