### ISSUE TITLE
[2.0.3] Vue module not found while building app

### ISSUE THREAD

**Issue by LeYom** [leezng/vue-json-pretty#129]
Hi,

I am using the library with quasar v2 (using vuejs 3).

By default the library is blocking the build :

```
 App • Chaining "UI" Webpack config
 App • Cleaned build artifact: "~/myproject/dist/spa"
 App •  WAIT  • Compiling of "UI" in progress...
 App •  DONE  • "UI" compiled with errors • 28923ms

 App •  ERROR  •  UI  in ./node_modules/vue-json-pretty/lib/vue-json-pretty.js

Module not found: Can't resolve imported dependency "Vue"
Did you forget to install it? You can run: npm install --save Vue


 App •  COMPILATION FAILED  • Please check the log above for details.
```
 
I have to add this configuration in my quasar configuration in order to solve the problem, by creating a alias Vue for the vue library :
```
chain.resolve.alias.set('Vue', 'vue')
```

I don't feel that is is a good way.

Regards,

**Comment by leezng** [comment]
Vue is peerDependencies, you need to install it yourself.

**Comment by liushuaikobe** [comment]
I got a similar error when run locally.

```
 ERROR  Failed to compile with 1 error                                                                                                                                                                                                                                                                    7:02:28 PM

This dependency was not found:

* Vue in ./node_modules/vue-json-pretty/lib/vue-json-pretty.js

To install it, you can run: npm install --save Vue

```

**Comment by LeYom** [comment]
vue is already installed, the module isn't found during the build phase because it is searching for 'Vue' module instead of the real one which is 'vue'

**Comment by leezng** [comment]
Try v2.0.4

**Comment by LeYom** [comment]
vue is already installed, the module isn't found during the build phase because it is searching for 'Vue' module instead of the real one which is 'vue'

**Comment by LeYom** [comment]
Sorry, to be late to respond. I was on holidays.

The 2.0.4 works fine. 

Thanks
