### ISSUE TITLE
[2.0.4] the value won't start a new line automatically

### ISSUE THREAD

**Issue by liushuaikobe** [leezng/vue-json-pretty#133]
I change the initial value in demo `Basic.vue` to:

``` json
{"appName":"helloworld","imageUrl":"https://example.com/example/hello/201232359/example_example_example.jpg"}
```

and the `imageUrl` is broken as shown.

![CleanShot 2021-08-18 at 11 30 54@2x](https://user-images.githubusercontent.com/2098020/129832539-e2de7fb8-3610-4238-b837-ec3d0417847d.png)

After I adding a `word-break: break-word` style, everything works well.

![CleanShot 2021-08-18 at 11 35 43@2x](https://user-images.githubusercontent.com/2098020/129832920-54367cde-be63-4cb6-abfc-c0d0fed48ea1.png)

**Comment by leezng** [comment]
Can your opinion help a PR?
