### ISSUE TITLE
Build runtime problem

### ISSUE THREAD

**Issue by Xeyos88** [leezng/vue-json-pretty#147]
Hi all,
after the build of my project i have the following error with the module:

`runtime-core.esm-bundler.js:6772 TypeError: Cannot read properties of undefined (reading 'deepCollapseChildren')
    at vue-json-pretty.js:1`
The same with the 'visibleData' property.

Any suggestion?

**Comment by Xeyos88** [comment]
The problem is in the version 2.0.5

**Comment by leezng** [comment]
Please try to use 2.0.4, 2.0.5 version has problems.
