### ISSUE TITLE
Missing comma

### ISSUE THREAD

**Issue by glennpierce** [leezng/vue-json-pretty#149]
When I try to display the following json

{ "ventive": { "name": "ventive", "organisation_name": "ventive", "project_name": "prototype", "campus_name": "nottingham", "interval": 60, "conn": { "user": "myuser", "password": "*****", "host": "myhost", "port": 5432, "database": "bmos" }, "sites": {} } }

The output I get is missing a comma between conn and sits as below.

> {
>    "ventive":{
>       "name":"ventive",
>       "organisation_name":"ventive",
>       "project_name":"prototype",
>       "campus_name":"nottingham",
>       "interval":60,
>       "conn":{
>          "user":"bmos",
>          "password":"cms823nvc",
>          "host":"carneab4.memset.net",
>          "port":5432,
>          "database":"bmos"
>       }"sites":{}
>    }
> }

I am using "vue-json-pretty": "^1.8.1"

Am I missing something obvious ?

**Comment by leezng** [comment]
This may be a bug of `1.x`, I tried to run it on 2.x and found that it was fine.

**Comment by tengxing** [comment]
> This may be a bug of `1.x`, I tried to run it on 2.x and found that it was fine.

Is there a good solution in version 1.8.2, because I use vue2,looking forward to your reply

**Comment by leezng** [comment]
closed at 1.8.3
