### ISSUE TITLE
How to use customValueFormatter Property

### ISSUE THREAD

**Issue by BullfroG21** [leezng/vue-json-pretty#154]
Hi, 

the documentation mentions the property customValueFormatter. However, I was not able to find an example how this property can be used. Is there somewhere a simple example for this property?

Thx

**Comment by leezng** [comment]
https://github.com/leezng/vue-json-pretty/blob/2c14ad7538297eb8c44a0985aa633fd2f12814fa/example/Basic.vue#L107
