### ISSUE TITLE
Cannot find module 'src/utils' or its corresponding type declarations.ts

### ISSUE THREAD

**Issue by BroJenuel** [leezng/vue-json-pretty#158]
Im using typescript, this is my error.
I am using Vue 3 with Vite, and TypeScript.
![image](https://user-images.githubusercontent.com/31676163/157637747-4f3a8cd2-fe92-411d-b875-2d817f22f757.png)

**Comment by leezng** [comment]
Please provide the version of the library you are using and the vue version

**Comment by BroJenuel** [comment]
I'm using latest Vue 3, vite, and typescript.. when building this error came out. although works in development mode, but when building it does not.
![image](https://user-images.githubusercontent.com/31676163/157636135-b1ff85f2-c3ca-4948-8c95-0652acb3190d.png)

**Comment by BroJenuel** [comment]
@leezng please help

**Comment by BroJenuel** [comment]
> Please provide the version of the library you are using and the vue version

opening the module and checking, my IDE tells that it cant find the 'src/utils'
![image](https://user-images.githubusercontent.com/31676163/157643920-bade5508-ddde-430e-88c8-0296039e7f45.png)

**Comment by BroJenuel** [comment]
anyone?

**Comment by souljorje** [comment]
@BroJenuel looks like @leezng should add `"src"` in package.json `"files"` field.

**Comment by leezng** [comment]
duplicate #121
