### ISSUE TITLE
publish latest 1.x & 2.x to npm 🙏

### ISSUE THREAD

**Issue by souljorje** [leezng/vue-json-pretty#165]
Please publish to npm after merging https://github.com/leezng/vue-json-pretty/pull/163 & https://github.com/leezng/vue-json-pretty/pull/164
UPD. please merge following fix for https://github.com/leezng/vue-json-pretty/pull/164 in advance:  https://github.com/leezng/vue-json-pretty/pull/166

**Comment by leezng** [comment]
Released.
