### ISSUE TITLE
Latest v2 release published on npm but not tagged on GitHub

### ISSUE THREAD

**Issue by zenflow** [leezng/vue-json-pretty#168]
Latest v2 release published on npm is `2.1.0` (published on May 11th, 2022).
But latest v2 release tagged on GitHub is `2.0.6` (tagged on November 11th, 2022).

Without the release on GitHub with release notes, it's hard when upgrading, to review what changes were made and if we are affected.

Is PR #160 the only change introduced in the 2.1.0 release? Or are there more?

**Comment by leezng** [comment]
Sorry, the release notes have been updated.

**Comment by zenflow** [comment]
Thank you so much @leezng !!!
