### ISSUE TITLE
Add carets next to brackets for expanding/collapsing

### ISSUE THREAD

**Issue by vincerubinetti** [leezng/vue-json-pretty#169]
Currently, you have to click directly on the brackets to expand/collapse. As far as I know, this UI behavior does not exist in any other product/program for a tree display like this. The Chrome dev tools shows nested objects with little ▸ symbols, for example. I don't think users will know to click on the brackets, and their mouse hitboxes are small enough that they may never hover over them by accident.

Adding ▸ and ▾ carets would be a good idea, and or making the hitbox for expanding/collapsing the whole row instead of just the bracket `<span>`.

**Comment by leezng** [comment]
@vincerubinetti 
Great idea, is it possible to turn your code into a configurable prop and contribute a PR to the project?

**Comment by vincerubinetti** [comment]
The part about adding the carets via a CSS pseudo element I think is a good idea, but the rest of the code is a hack. Shouldn't need to use a mutation observer when there's actual Vue lifecycle hooks to listen to.

So the above code can't be (shouldn't be) copied and pasted into a PR, no. I can try to look at the code to do a real PR, but I have no familiarity with the code and don't have much time.
