### ISSUE TITLE
double quotation mark for key

### ISSUE THREAD

**Issue by kinoooolu** [leezng/vue-json-pretty#17]
Please add the double quotation mark for the keys so that it can look the same as the json content.

![image](https://user-images.githubusercontent.com/23189885/50267414-1ceb4e80-0462-11e9-9dd1-426786225ac2.png)

**Comment by dvlden** [comment]
No. That should be an option only, if @leezng is willing to create it.
Current way is the way to go by default...

**Comment by leezng** [comment]
yes. I will make it as a option.

**Comment by leezng** [comment]
release at 1.6.0
