### ISSUE TITLE
vjs-tree__node overflows beyond parent container

### ISSUE THREAD

**Issue by jvalrog** [leezng/vue-json-pretty#180]
I have the following problem with an Ant Design Popover:

![image](https://user-images.githubusercontent.com/456311/180983119-c6401c46-c3bf-4a78-92c4-d4949b839cc6.png)

The "vjs-tree__node" div is bigger than the popover container. 

After debugging it with the CSS layout inspector, I found that the indents are implemented with empty child containers as can be seen.

To fix that I removed those empty containers and applied a margin to that line:

![image](https://user-images.githubusercontent.com/456311/180983451-eb9fbdcb-19ea-41d0-9684-e0841e03fa43.png)

The problem is solved and the parent container increases its width to host the children without problems.

Wouldn't be better to implement indents as css margins??

**Comment by leezng** [comment]
Maybe you can add css style to the class of value, for example `word-break`.
