### ISSUE TITLE
Custom Formatter

### ISSUE THREAD

**Issue by k0nstant1na** [leezng/vue-json-pretty#185]
Ιs there a way to highlight a specific node (key-value) if it has a specific value?
customValueFormatter prop highlight only the value.

**Comment by leezng** [comment]
I have 2 suggestions:
1. Mark each node with the class attribute, you can add styles according to different class names, for example, you can use the path of the current node, but when the level is very deep, the class name will become very long.
2. Add a new attribute, such as `pathHighlightList`, which can automatically highlight at the component layer if it meets the conditions.

**Comment by leezng** [comment]
Now, you can use `slot` to achieve.
