### ISSUE TITLE
ssr rendering errors with 1.9.0 (vue 2)

### ISSUE THREAD

**Issue by simllll** [leezng/vue-json-pretty#188]
since the latest release (1.9.0) we have two errors which makes the app unusable:

`DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.`

`TypeError: Cannot read properties of undefined (reading '$scopedSlots')`

both of them occur at the same time, and it seems it has something to do with a "comment" block. the renderes (ssr) html of it is:
![image](https://user-images.githubusercontent.com/5757263/184951122-f4f27467-3479-4a06-9eff-a6108b745b49.png)

the problematic line according to the .appendChild error is the `<!-- >` in the 3rd block, block 1 & 2 also have the comment in there, but somehow it's not an issue here?

the json we format is nothing special:
```json
{
        email: 'obfuscated@gmail.com',
        firstName: 'NameObfuscated',
        lastName: 'LastNameObfucstaed',
        phone: '+46...numberOnlyObfocusated'
    } 
```

**Comment by simllll** [comment]
Okay, while looking into this in more details I found something that is also bugging me:
 ERROR in /buddy/hokify-server-1/node_modules/vue-json-pretty/lib/vue-json-pretty.js 1:5166
  Module parse failed: Unexpected token (1:5166)
  You may need an appropriate loader to handle this file type, currently no loaders are configured 

it seems the "?" (optoinal chaining) is not supported in tihs case, even though I'm at node 16. the only way around this is to transpile the vue-json-pretty library in nuxt. Did the output change somehow?

**Comment by simllll** [comment]
It works on dev environemnt now with the transpile option, but on the production I still get the appendChild error
```
df2a723.js:2 DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
    at Object.appendChild (https://hokify.com/admin/_nuxt/df2a723.js:2:53656)
```

**Comment by leezng** [comment]
You can configure babel to try(optoinal chaining)
```js
{
  css: ["vue-json-pretty/lib/styles.css"],
  plugins: ["~plugins/vue-json-pretty"],
  build: {
    // ....
    transpile: ["vue-json-pretty.js"],
    babel: {
      presets: ["@nuxt/babel-preset-app"]
    }
  }
}
```

**Comment by simllll** [comment]
Yeah I got it working now, but need to transpile the library. I guess webpack4, which is used by nuxt2, can't handle optional chaining without additional configuration. My question is if the library could generate an output that is compatible with webpack, which would make things easier again ;-)

**Comment by leezng** [comment]
Yes, this can be handled in the packaging process.
