### ISSUE TITLE
Feature: Highlight selected item in tree mode

### ISSUE THREAD

**Issue by rubanraj54** [leezng/vue-json-pretty#19]
Hi @leezng 

I've seen this pull request #14 is closed since "selectedPath" is conflicting with "selectedType".

However, I would like to see this feature with a configurable option.

You can let the user choose whether they want to highlight the selected item or not in both cases (tree or checkbox view).

What's your opinion on this idea? If you think this makes sense, let me know I will make a new pull request with this feature.

Cheers,
Ruby.

**Comment by leezng** [comment]
Hi.
There is such a multi-selection case, when I select an object and the entire array, how should I highlight this time? I think that you can only achieve highlighting when you select an item.

![image](https://user-images.githubusercontent.com/13777294/54414561-8a8eda00-4734-11e9-9425-258995b8e66e.png)

**Comment by rubanraj54** [comment]
Hi @leezng 

Ok I understand your point. In multi-selection mode at least there is some checkbox visually identification to the user that the items are selected.

But in **tree**  mode, after selecting an object or attribute, there is no visual identification in the JSON tree that an object or attribute is being selected. 

I would suggest if you add a class  to the outer <div> element of the selected object/attribute for example ".selected", then the users case apply their own styles for the element.

Also, this plugin lacking the custom styling.
For example,
-  Font color
-  Mouse hover highlighting color
-  Selected item background color in tree mode.

I also see in your code that, you are binding styles on mouseover and mouseout event.

![Screenshot from 2019-03-15 12-48-16](https://user-images.githubusercontent.com/10024405/54429453-e7809500-4720-11e9-8d85-adaac4d25796.png)

On mouseout event you're binding **transparent** as a background color, I would say you can apply **transparent** style if user didn't give selected item background color in the config, else apply user background color if they provide.

What do you think about on this opinion?

Cheers,
Ruby.

**Comment by leezng** [comment]
Thank you very much for your suggestion, I agree with your idea of using class(.selected or ...), which will make it easier for users to customize by style override.

In addition, the main problem with highlighting an item is the lack of plugin, because multiple selection and single selection should be mutually exclusive. But in the plugin, there is a mode called "both"(tree && checkbox), which leads to some difficult problems. So I'm gonna fix this design flaw 
(cc9ea77). For example, checkbox and tree will not exist at the same time, so that an item can be highlighted during single selection.

**Comment by rubanraj54** [comment]
Good to hear that and thanks for considering the suggestion.

Looking forward to seeing "highlighting the selected item" feature in the new release.

Cheers,
Ruby.

**Comment by KrishnaPG** [comment]
This component is a good work, and this suggestion of custom styling definitely improves the usability. Just wanted to say thank you for the efforts on this.
