### ISSUE TITLE
Error: Invalid left-hand side in assignment, if JSON key has special chars (hyphen, underscore etc..)

### ISSUE THREAD

**Issue by ChethanEJ7** [leezng/vue-json-pretty#192]
I appreciate the editable feature for the JSON values, it works like a charm. But I see there is some assignment operator missing issues.

Description:
In the JSON, if the key is a string without any special characters, the JSON value is modified and works as expected.
But if the JSON key is `**-**` example `**install-mode**`, the editable option fails with the following error:
Uncaught SyntaxError: Invalid left-hand side in assignment
    at new Function (<anonymous>)
    at S (vue-json-pretty.js?0c42:1:1)
    
Expected: 
The editable option is successful when the JSON key has some special characters such as hyphen (-), underscore (_) etc..

Actual: 
The editable option doesn't work if the key has a hyphen/underscore.

**Comment by leezng** [comment]
@ChethanEJ7 
Thanks for your feedback, it may be a bug.

**Comment by ChethanEJ7** [comment]
Yes, seems like a bug. Now editable works fine, when key is Alphanumeric only without any spl chars.

It would help me for my application, if the bug can be fixed asap😉

**Comment by ChethanEJ7** [comment]
Thanks.! Seems to work as expected.
