### ISSUE TITLE
How do you use selectable nodes?

### ISSUE THREAD

**Issue by drilus** [leezng/vue-json-pretty#197]
I don't understand how to use selected nodes. I've read the documentation and looked at the demo but there are no examples to go off of.

```html
           <vue-json-pretty
              v-model="claims"
              showSelectController
              highlightSelectedNode
              :style="maxheight"
              editable
              selectableType="single"
              :selectedValue="selected"
            ></vue-json-pretty>
```

I've set the v-model to my "claims" json object and selectedValue is bound to a "selected" prop.
I've enabled:
showSelectController
highlightSelectedNode
selectableType="single"

However, I have no idea how to use the selectedValue or get the node value, etc like in the demo. Clicking on the select area/node does nothing (no highlighting, doesn't select the radio buttons) and returns no errors.

**Comment by drilus** [comment]
I was able to get it working. I was using selectedValue instead of selectedValue.sync.

**Comment by zepingFISH** [comment]
> 我能够让它工作。我使用的是 selectedValue 而不是 selectedValue.sync。

Why did he fail to win the single election

**Comment by zepingFISH** [comment]
> 我能够工作。我使用的是 selectedValue 而不是 selectedValue.sync。

<vue-json-pretty
          :selectedValue="a"
          rootPath="$"
          :data="response"
          :showSelectController="true"
          selectableType="single"
          :highlightMouseoverNode="true"
          :highlightSelectedNode="false"
          :style="contentStyleObj">
        </vue-json-pretty>


a: '',

**Comment by zepingFISH** [comment]
> 我能够工作。我使用的是 selectedValue 而不是 selectedValue.sync。

<vue-json-pretty
          :selectedValue="a"
          rootPath="$"
          :data="response"
          :showSelectController="true"
          selectableType="single"
          :highlightMouseoverNode="true"
          :highlightSelectedNode="false"
          :style="contentStyleObj">
        </vue-json-pretty>
a: ''
