### ISSUE TITLE
Additional Classes for selectable key and value

### ISSUE THREAD

**Issue by KrishnaPG** [leezng/vue-json-pretty#20]
This project is a great work. It is helpful. Thank you.

One small drawback is: Currently all the keys and values are styled the same. I would like to showcase the **selectable** keys and values differently so that users can immediately see only few keys and values are clickable. (Background color on hover is good, but without hovering on the node, just by looking at all the nodes it is difficult to say which nodes are clickable and which are not).

When using the function `pathSelectable` to customize the selectable behavior of a node, could you please add the classes `vjs__selectable__value` , `vjs__selectable_key` to the value and key respectively so that:
- we can customize the selectable key css, and selectable value css each separately
- and customize the mouse appearance, e.g. change the mouse to, say, pointer or hand etc. only for the selectable keys and values etc.

For example, the below screenshot illustrates the css overrides, where the usual keys and values take grey colors, and only the selectable keys and selectable values highlighted with different color, and underline, so that it is visually easy for users to understand that these keys and values are different and special.

![image](https://user-images.githubusercontent.com/4610831/54537004-c2f21a80-49b7-11e9-9e7f-f4f700921e1b.png)

**Comment by leezng** [comment]
Every key and value has className now. And the selectable tree has s special className called `is-selectable`.
