### ISSUE TITLE
Click handler should have parameter to identify the source component

### ISSUE THREAD

**Issue by KrishnaPG** [leezng/vue-json-pretty#21]
When you have multiple `vue-json-pretty` components on the page (say, created in a for loop), the click handler does not know which one is causing this event.

Consider this scenario: there are multiple json structures on the page, each one with same schema, but from different server. Whenever you click on a node in one of these, you should contact the respective server for more details on that node. 

Currently it is not possible to do this, since the click-handler does not give back any information about the source component where the event is raised. 

Also, is there anyway this `vue-json-pretty` could hold some user data attached with each of its instance (at the component level at the top) that it will supply back to the click handler? For example, would like to associate the server url with each `vue-json-pretty` instance, so that in the click handler we can:
````
<panel v-for="(server) in servers">
  <vue-json-pretty :data="svcDetails[server]" @click="onDetailsClick" :attachData="server"></vue-json-pretty>
</panel>

onDetailsClick: function(path, value, attachedData) { 
    const server = attachedData; // get the attached data
    axios.post(server, body: value);  // use the currently selected value with attached data somehow
}
````

**Comment by leezng** [comment]
You can define the `ref` attribute of each tree if needed. In addition, if you want to have some extra  parameters, I think it should be added on the click-handler,  because in most cases it doesn't need to have extra parameters. For example:

```vue
<panel v-for="(server) in servers">
    <vue-json-pretty :data="svcDetails[server]" @click="onDetailsClick(...arguments, server)"></vue-json-pretty>
</panel>

onDetailsClick: function(path, value, server) {
    axios.post(server, body: value);  // use the currently selected value with attached data somehow
}
```

**Comment by KrishnaPG** [comment]
Yes. Thank you.
