### ISSUE TITLE
Why the deep prop is not reactive? (为什么唯有deep prop不是响应式的?)

### ISSUE THREAD

**Issue by heavenkiller2018** [leezng/vue-json-pretty#213]
为什么唯有deep prop不是响应式的? 其他像showLineNumber，showLineNum都是响应式的，这是出于什么考虑呢?

**Comment by leezng** [comment]
The calculation of the deep attribute consumes more performance, so the responsiveness is not currently enabled.
But the final design goal is to support responsiveness.

**Comment by heavenkiller2018** [comment]
deep这个prop感觉没起到作用啊，不管我设成多少，显示都是全部展开, 而且改变其他响应式prop时，deep也没起到作用，也都是全部展开的。唯有我手动刷新组件key，这时候才会按照实际deep进行展示，这是个bug吧
