### ISSUE TITLE
Hide or display null and undefined values

### ISSUE THREAD

**Issue by JaviOverflow** [leezng/vue-json-pretty#214]
When a value is null or undefined, it shows as empty. How can I hide such elements?

**Comment by leezng** [comment]
It is a bug, duplicate with #205, fixed in #207.

**Comment by JaviOverflow** [comment]
Thanks for the quick reply! I see that the last release is from Aug 28 - Do you have any idea when this change will get to the production release?

**Comment by leezng** [comment]
release 1.9.3 & 2.2.3
