### ISSUE TITLE
why not working vue2 json-pretty ?

### ISSUE THREAD

**Issue by wjdrbs96** [leezng/vue-json-pretty#217]
```vue
<template xmlns="http://www.w3.org/1999/html">
  <div>
    <vue-json-pretty :data="{ key: 'value' }" :deep="test"/>
  </div>
</template>

<script>

import VueJsonPretty from 'vue-json-pretty';
import 'vue-json-pretty/lib/styles.css';

export default {
  name: "json-pretty",
  components: {
    VueJsonPretty
  },
  data: () => ({
    test: 2,
  }),

  methods: {
  }
}
</script>
<style scoped>
</style>
```

```
npm install vue-json-pretty@v1-latest --save
```

I installed it with the above command.

<br>

## `Result`

<img width="134" alt="스크린샷 2022-10-31 오전 12 11 45" src="https://user-images.githubusercontent.com/45676906/198886171-ce76c923-0dc6-4f42-9128-d75645481453.png">

- "vue": "^2.5.16"
- "vue-json-pretty": "^1.9.2",

**Comment by leezng** [comment]
We were unable to reproduce your problem, please check your project, or provide a copy at https://codesandbox.io.
