### ISSUE TITLE
Separate CSS from JS?

### ISSUE THREAD

**Issue by dvlden** [leezng/vue-json-pretty#22]
Just for convenience, instead of overriding the default CSS when necessary, it'd be nice if it can be imported separately. (SCSS or CSS, w/e)

I prefer control over styling, rather than just having it thrown into DOM as is.

Two options here... But perhaps the best would be:

- Create a bundled output, that includes both JS and CSS and create another output where it has CSS and JS separately in build.

**Comment by leezng** [comment]
I prefer the way to separate LESS or SCSS, but now it seems that it is easier to provide CSS and JS separately in the package.

**Comment by dvlden** [comment]
Revisit. Any update on this? This is a big issue for me, especially because of CSP headers.

**Comment by leezng** [comment]
Try 1.7.0
