### ISSUE TITLE
Type of Data prop

### ISSUE THREAD

**Issue by tpoxa** [leezng/vue-json-pretty#224]
vue-json-pretty works great with any JSON data even string which is still valid JSON but not a JSON object
Only problem that I am having a lots of vue warnings regarding invalid type of a prop.

```shell
Invalid prop: type check failed for prop "data". Expected Object, got String with value ...
```

Can we allow data to be a string too?

Thanks

**Comment by leezng** [comment]
Currently, the data type is set to object, which may be a problem:
https://github.com/leezng/vue-json-pretty/blob/06b9730a298dd1621ee20a2587ee7619921dd101/src/components/Tree/index.tsx#L21

**Comment by tpoxa** [comment]
Yes. I know.
Can you allow to be prop a STRING or OBJECT?
