### ISSUE TITLE
[Bug] Spaces are not added between keys and values

### ISSUE THREAD

**Issue by staghouse** [leezng/vue-json-pretty#234]
My assumption would be that the rendered result would match a the written object:

```js
const example = {
  "test": "1",
  "something": {
    "something2": [
      "s"
    ]
  }
}
```

Note the spaces between semi-colons and the values

See below screenshot:

<img width="298" alt="Screen Shot 2023-02-26 at 12 51 36 PM" src="https://user-images.githubusercontent.com/1939508/221427409-290ab210-b26a-4c4b-bfd4-10b62a642d35.png">

**Comment by leezng** [comment]
@staghouse Which component version and vue version are you using?

**Comment by staghouse** [comment]
> @staghouse Which component version and vue version are you using?

Vue 3 and the latest package. Further, I am using it in VitePress.
