### ISSUE TITLE
Selector is not working when using Vue 2

### ISSUE THREAD

**Issue by JoshuaeKaiser** [leezng/vue-json-pretty#236]
Hi, 

tried using the selectior functionality in vue 2

I have tried specifying the selectedValue prop as it says in the docs and have all the appropriate flags set. When I click a selector radio button nothing happens it fails to highlight and I fail to get an event on the @selectedChange handler.

Any help greatly appreciated.

<img width="460" alt="Screenshot 2023-03-13 at 16 15 26" src="https://user-images.githubusercontent.com/17850490/224761927-7b742a2b-751b-4b29-840a-e30f60ca8585.png">
<img width="419" alt="Screenshot 2023-03-13 at 16 15 41" src="https://user-images.githubusercontent.com/17850490/224761945-55737ade-b02f-40ee-962f-fd7402cfa4ab.png">

**Comment by leezng** [comment]
In Vue2 you must use [`sync-Modifier`](https://v2.vuejs.org/v2/guide/components-custom-events.html#sync-Modifier):

```vue
<vue-json-pretty:selected-value.sync="selectedValue" />
```
