### ISSUE TITLE
Uncaught (in promise) TypeError: e3._self is undefined

### ISSUE THREAD

**Issue by a492858187** [leezng/vue-json-pretty#246]
引入后这个报错要怎么解决
Uncaught (in promise) TypeError: e3._self is undefined
    r vue-json-pretty.js:1
    renderComponentRoot runtime-core.esm-bundler.js:893
    componentUpdateFn runtime-core.esm-bundler.js:5029
    run reactivity.esm-bundler.js:160
    setupRenderEffect runtime-core.esm-bundler.js:5155
    mountComponent runtime-core.esm-bundler.js:4938
    processComponent runtime-core.esm-bundler.js:4896
    patch runtime-core.esm-bundler.js:4488
    mountChildren runtime-core.esm-bundler.js:4684
    mountElement runtime-core.esm-bundler.js:4593

**Comment by leezng** [comment]
Please provide more details.

I think it might have something to do with your project configuration.
