### ISSUE TITLE
编辑没法确认

### ISSUE THREAD

**Issue by Mort1f** [leezng/vue-json-pretty#248]
只能调出输入框，输入了值，没法确认。改不了数据

**Comment by leezng** [comment]
目前的交互是`click-outside`模式，点击外部空白即保存关闭输入框

**Comment by SheepYang1993** [comment]
@leezng 点击了外部也不能关闭输入框

**Comment by leezng** [comment]
@SheepYang1993 麻烦提供一个复现demo https://codesandbox.io/ ，或更详细的信息
