### ISSUE TITLE
normalizeKey is not a function

### ISSUE THREAD

**Issue by momtboy** [leezng/vue-json-pretty#250]
vue ^3.2.47
vite ^4.3.5

导入报错

**Comment by tripflex** [comment]
@leezng what was the solution for this?

**Comment by leezng** [comment]
@tripflex Please provide more detailed information or online links, such as vue version, component version, etc.

**Comment by tripflex** [comment]
```
"vue": "^3.3.4",
"vite": "^4.2.0",
```

Anytime I include `vue-json-pretty` i get this error
