### ISSUE TITLE
Why did the value change back after I finished editing

### ISSUE THREAD

**Issue by FZmz** [leezng/vue-json-pretty#251]
<vue-json-pretty
          :editable="true"
          :data="submitConfigJSON.data"
          :show-line="true"
          :show-line-number="true"
          :show-length="true"
          :highlight-selected-node="true"
          :show-icon="true"
          :deep="3"
          editableTrigger="click"
          selectableType="single"
        />
Why doesn't editing work

**Comment by leezng** [comment]
You should use `v-model:data`.

**Comment by xubaobao19940428** [comment]
I used the same function, also using v-model:data,
Editing still doesn’t take effect
`<vue-json-pretty v-model:data="jsonData" :editable="true" :show-line="true" :show-line-number="true"
            :show-length="true" :highlight-selected-node="true" :show-icon="true" :deep="3" />`

**Comment by SheepYang1993** [comment]
@leezng 我这编辑后，也是不能修改文本
