### ISSUE TITLE
net::ERR_ABORTED 504 (Outdated Optimize Dep)

### ISSUE THREAD

**Issue by ueiheng** [leezng/vue-json-pretty#277]
net::ERR_ABORTED 504 (Outdated Optimize Dep)

**Comment by ueiheng** [comment]
<img width="679" alt="image" src="https://github.com/user-attachments/assets/102c165e-65f6-4254-8f13-66affc796d89">

**Comment by leezng** [comment]
Not related to the project.
https://stackoverflow.com/questions/75883720/504-outdated-optimize-dep-while-using-react-vite
