### ISSUE TITLE
Could set default `expand or collapse` with specifect level?

### ISSUE THREAD

**Issue by thearabbit** [leezng/vue-json-pretty#3]
![image](https://user-images.githubusercontent.com/4495160/36258438-39293c5a-128d-11e8-8d52-7e240bdddf27.png)

**Comment by leezng** [comment]
Yeah, you can use the property of `deep` , for example:
```vue
<vue-json-pretty :deep="1"></vue-json-pretty>
```

**Comment by thearabbit** [comment]
It works fine.
