### ISSUE TITLE
How to start with closed JSONs (collapsed)

### ISSUE THREAD

**Issue by syberkitten** [leezng/vue-json-pretty#30]
How is it possible to start with collapsed (closed) view of the JSON?
Right now it's by default expanded....

**Comment by giodall** [comment]
check the deep option

**Comment by douglassllc** [comment]
If I set deep="2" it works on the initial usage of the component.  If I click to expand lower then deep="2", the parent component remains instantiated and I dynamically load new data.  The new data has the same expanded levels, but my goal is to reset the depth back to 2.  Is there a way to achieve this if the component is not destroyed and recreated?
