### ISSUE TITLE
How to update the data when the json value changes?

### ISSUE THREAD

**Issue by janmichaelyu** [leezng/vue-json-pretty#31]

**Comment by leezng** [comment]
Update the data? Can you describe it in more detail?

**Comment by janmichaelyu** [comment]
Say I'm passing 
let jsonData = { temp:'val'}

<vue-json-pretty
      :path="'res'"
      :data="jsonData"
      @click="handleClick">
    </vue-json-pretty>

and the component shows {temp:'val'} correctly.

If the parent component changes jsonData to {temp:'newVal'}, the child component doesn't seem to change.

**Comment by leezng** [comment]
It will auto changed, see the [demo](https://leezng.github.io/vue-json-pretty/).

**Comment by janmichaelyu** [comment]
Alright, thanks! I'll have to figure out what I did wrong.
