### ISSUE TITLE
Feature request: emit an event whenever visibility changes

### ISSUE THREAD

**Issue by jclark-dot-org** [leezng/vue-json-pretty#32]
I'm using this component inside a long list of items, so I'm using https://github.com/Akryum/vue-virtual-scroller to improve performance.  I'm using its `DynamicScroller` which supports variable height entries, but which must be notified when an item's height changes.  It would be useful for vue-json-pretty to emit an event when the user clicks on brackets to toggle visibility of nested data.

I took a look at the source; I see that the brackets mixin emits an 'update:visible' event to allow binding sync, but it looks like vue doesn't bubble that event up outside of vue-json-pretty, as I can't seem to bind them in my code.

**Comment by leezng** [comment]
If you can listen the click events inside the component (whether the user clicks on brackets or other elements), Is this able to fulfill your request?

**Comment by jclark-dot-org** [comment]
Yes, that should be sufficient to allow me to inform the dynamic scroller of a height change.

A related question: Is there any way to capture the current expanded/collapse state, and re-apply it?  I'm finding that the scroller, by dynamically adding/removing elements from the page, is causing every vue-json-pretty to lose it's state when it scrolls off and back on.  I think with a click event on brackets (if it includes location and open/closed state) I could track the state, but don't know how I could re-apply it.  If not, I'll explore this later; for now, a click event that also fires on brackets (or a separate bracket click event) would be a huge help.

**Comment by leezng** [comment]
I have created a new branch and removed `stopPropagation` on the click event. You can pull the code and test it.

[branch url](https://github.com/leezng/vue-json-pretty/tree/discuss-event-propagation)

**Comment by jclark-dot-org** [comment]
Sorry for not following up sooner - my project had to be put on hold for a couple of months.  This changed helped, but the critical click events - those that expand and collapse brackets - were still not coming through.  I found two more `@click.stop`  handlers in `brackets-left.vue` which handle the actual expansion/collapsing; removing `stopPropagation` here makes everything work.  I can submit a PR if you'd like.
