### ISSUE TITLE
Feature Request: showLineNumber

### ISSUE THREAD

**Issue by runyasak** [leezng/vue-json-pretty#35]
Hi, I always use `vue-json-pretty` component to render beautiful JSON data.

In my opinion, it should show line number of JSON data as option.
Is it interesting or useful? Please, let me know your ideas and comments.

Thank you,
World

**Comment by leezng** [comment]
![image](https://user-images.githubusercontent.com/13777294/61707915-19180580-ad7e-11e9-9e15-e6595bbca5a6.png)

Like this?

**Comment by runyasak** [comment]
@leezng 
Yes, like that.
It would be great if it is an option and can change colour.

Actually, you can assign me to do this issue. 😂

**Comment by leezng** [comment]
@runyasak 
If you can help me to do this issue, you're welcome to do. Maybe showing the numbers is more important, the color can be deferred.

**Comment by runyasak** [comment]
Thanks @leezng,

I will come up with PR later.
Please, do not forget to review my PR. 😁

**Comment by runyasak** [comment]
Hi, sorry for waiting.

I have created PR but didn't finish, need some review & advice.
Please, review on this PR. #48

**Comment by jakubstankowski** [comment]
Hi!

Any news about show line number feature ? 
It will be great option

**Comment by leezng** [comment]
There are some unsolved problems, such as how to calculate those unexpanded

**Comment by runyasak** [comment]
Hi, long time no see.

I have tried to develop.
However, I have stuck with components recursive, as you can see from my PR.

If you have any feedback or solution, please give me some advice or suggestion.
I will make it work as fast as I can. 😎
