### ISSUE TITLE
data的排序问题

### ISSUE THREAD

**Issue by mdily** [leezng/vue-json-pretty#4]
在使用中发现会对data中的下级对象数据根据key来排序，是否可以增加参数来控制是否需要排序？现在哪里的代码是对data进行排序的，我没有发现，能否告知？谢谢

**Comment by leezng** [comment]
请提供一个 example，我这边看不到你描述的情况 @mdily

**Comment by mdily** [comment]
![image](https://user-images.githubusercontent.com/21079657/36892956-61d5c79e-1e41-11e8-9c7f-17d639e8ad4f.png)
这个是后端返回的数据，tran_log下面是不按照key排序的
![image](https://user-images.githubusercontent.com/21079657/36893016-906ee2f2-1e41-11e8-8151-f1c0a2f76572.png)
这个是显示的数据，tran_log下面就是按照key排序的

**Comment by leezng** [comment]
> ECMA-262（ECMAScript）第三版中描述，`for-in` 语句的属性遍历顺序由属性构建的顺序决定。
> ECMA-262（ECMAScript）第五版规范中，`for-in` 语句的遍历的顺序是没有被规定的。

现代新版浏览器基本都按照第五版规范执行，而在该项目中使用 `vue` 的 `v-for` 遍历对象，对象本身是无序的，也就无法保证顺序。

**Comment by mdily** [comment]
ok，了解了，在vue的文档中也找到了相关解释https://cn.vuejs.org/v2/guide/list.html#%E4%B8%80%E4%B8%AA%E5%AF%B9%E8%B1%A1%E7%9A%84-v-for

**Comment by mdily** [comment]
能否可以修改Object.key()的值来做到对for-in的顺序构建

**Comment by leezng** [comment]
Object.keys() 的实现原理跟 for-in 是一致的

**Comment by mdily** [comment]
ok，谢谢，已经改成数组
