### ISSUE TITLE
当data为字符串时显示多了一个undefined的key

### ISSUE THREAD

**Issue by notomorow** [leezng/vue-json-pretty#42]
当data为字符串时显示多了一个undefined的key，建下图描述
![企业微信截图_8300be25-53dd-48a0-b851-d1e1347dff93](https://user-images.githubusercontent.com/12589944/63666127-e770df00-c800-11e9-94b0-4441125374d2.png)
![企业微信截图_895d96a2-5a17-407f-9be3-9d768ae16d05](https://user-images.githubusercontent.com/12589944/63666132-eb9cfc80-c800-11e9-97bf-e9dc8787a3c7.png)

**Comment by leezng** [comment]
感谢反馈，1.6.2已修复

**Comment by notomorow** [comment]
👍
