### ISSUE TITLE
Is it possible not to collapse brackets on click?

### ISSUE THREAD

**Issue by k2042** [leezng/vue-json-pretty#43]
In a displayed object, if I click on {} or [] brackets, they are collapsing. Can I turn this feature off somehow?

**Comment by leezng** [comment]
It can be a new feature.

**Comment by k2042** [comment]
It would be great. The thing is, while collapsing nodes is useful, collapsing the root is not always good. In my case, I wanted to turn off collapsing of the root, while the inner nodes remain collapsible.

**Comment by leezng** [comment]
release 1.6.3
