### ISSUE TITLE
Commas and quotes missing when selected

### ISSUE THREAD

**Issue by MoYummy** [leezng/vue-json-pretty#5]
![image](https://user-images.githubusercontent.com/8344384/39860442-eb3ba9f4-546f-11e8-8f2c-81920bcac1a6.png)

https://github.com/leezng/vue-json-pretty/blob/2af2d844774836f00dea68cc0f3d9c2309f6c5fd/src/assets/less/tree.less#L17
https://github.com/leezng/vue-json-pretty/blob/2af2d844774836f00dea68cc0f3d9c2309f6c5fd/src/assets/less/tree.less#L34

Is it possible for the selection of these two symbols to be configurable?

**Comment by leezng** [comment]
It's a bug.

**Comment by MoYummy** [comment]
Thanks a lot.
BTW, it would be better if it has a gutter for line numbers and a count for length of array or object keys (neither selectable)

**Comment by leezng** [comment]
@MoYummy 
I think this is a good suggestion, you can open a new issue for it.
