### ISSUE TITLE
when use it in production, it crashed, below is the snapshot

### ISSUE THREAD

**Issue by blesstosam** [leezng/vue-json-pretty#50]
<img width="583" alt="WX20191105-131628@2x" src="https://user-images.githubusercontent.com/26403700/68180693-984ce480-ffcf-11e9-995d-5dab348ce291.png">

**Comment by leezng** [comment]
Please provide a demo.

**Comment by blesstosam** [comment]
maybe its my app's problem, 1 closed this issue! thank you !
