### ISSUE TITLE
Is there a way to show big json ?

### ISSUE THREAD

**Issue by Azurx** [leezng/vue-json-pretty#55]
When dealing with a big json, the CPU/MEM usage of chrome process will grow fast and the browser page will load slowly or even not display.

There is a sample json(size 1MB) in the attachment, copy and paste in the [demo](https://leezng.github.io/vue-json-pretty) page can reproduce this condition. MEM usage of process will rich to nearly 2GB.

[sample_1M.txt](https://github.com/leezng/vue-json-pretty/files/4284968/sample_1M.txt)

**Comment by danieljpalmer** [comment]
Flagging that I too am encountering this issue, which is a shame because this is such a great library otherwise. Looking forward to V2!

**Comment by leezng** [comment]
This feature is supported in 2.x, and the master will be switched to a new version in the near future.

**Comment by danieljpalmer** [comment]
@leezng Does this mean this library plans to no longer be compatible with Vue 2?

**Comment by leezng** [comment]
Consider whether some useful features will be merged into 1.x, so 1.7 or 1.8 will be the last version that supports vue2, and version 2.0 will be the main version for long-term maintenance.
