### ISSUE TITLE
Question: how do I select all JSON content programmatically?

### ISSUE THREAD

**Issue by mtermoul** [leezng/vue-json-pretty#60]
I want to add a `copy` button next to `vue-json-pretty`. Once the button clicked, I want to do the following:
a- Select all content of `vue-json-pretty` (highlight all the json inside)
b- Copy the selected json in the clipboard.

**Comment by bob-lee** [comment]
@mtermoul you provide json data to `vue-json-pretty` and want to do something with json data on button click. I guess nothing to do with this package.

**Comment by leezng** [comment]
You can use v-model for selected control.

Copy event must be done by yourself using js.
