### ISSUE TITLE
这种格式的json，提取path时有处理办法么

### ISSUE THREAD

**Issue by wangmin19861205** [leezng/vue-json-pretty#63]
![image](https://user-images.githubusercontent.com/7638971/84100890-5db49a00-aa3f-11ea-845f-feaa0485f938.png)
会导致提取的path路劲不正确

**Comment by wangmin19861205** [comment]
{"data":[{"statusDesc":"正常","role":0,"ip":"qqqqq","heartbeatSupport":3,"weight":10,"serviceInfo":{"com.test.test1.test2.test3.test3.test4.test6":{"wwwwwwwwww":1}},"env":1,"cell":"","version":"qqqqqqqqq"}]}

其中的这一串     com.test.test1.test2.test3.test3.test4.test6

**Comment by Yangjia23** [comment]
@wangmin19861205 你解决了嘛

**Comment by Yangjia23** [comment]
@wangmin19861205  你可以设置 showSelectController="false" 将左侧单选隐藏，同时在点击事件中获取 当前选中的数据

**Comment by wangmin19861205** [comment]
恩    问题在于    他把数据中的key值”com.test.test1.test2.test3.test3.test4.test6“，与path路劲res.data[0]拼接了，所以得到的选中path为res.data[0].com.test.test1.test2.test3.test3.test4.test6
