### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by rchl** [leezng/vue-json-pretty#67]
Could you please release a new version with the latest changes?

I just noticed that it has a change that would make a difference for me. Namely removing whitespace around string values (https://github.com/leezng/vue-json-pretty/commit/15d8ff7e5229ede92f8f139347e4204784cba98b#diff-7a5275c00fd81236fde90a0ce0f491f1R4).

**Comment by leezng** [comment]
Yes, it will be released soon.

**Comment by rchl** [comment]
Sorry but how soon? :)

**Comment by leezng** [comment]
release 1.6.4

**Comment by rchl** [comment]
Can I ask for a new release since #71 was fixed? :)

**Comment by leezng** [comment]
@rchl release 1.6.5

**Comment by rchl** [comment]
New release please (now with 2577a7722254d27293519778f868a4cfe38a3898)? :)
