### ISSUE TITLE
Question: can I collapse certain named field?

### ISSUE THREAD

**Issue by bob-lee** [leezng/vue-json-pretty#68]
Thanks for this nice library. I am using on my report page to show various query results.
One of the result contains an array with lots of items and I wonder:
if I can make the field to be collapsed by default and just showing items count.
```
...
requests: [...] // 3 items
```

**Comment by folmert** [comment]
You can set `:show-length="true"` and `:deep="1"` but then every other node on that level will be collapsed as well.
