### ISSUE TITLE
怎么阻止数据折叠

### ISSUE THREAD

**Issue by jieorjie** [leezng/vue-json-pretty#84]
怎么阻止数据折叠

**Comment by leezng** [comment]
https://github.com/leezng/vue-json-pretty/blob/dev/README.zh-CN.md#props

**Comment by jieorjie** [comment]
> https://github.com/leezng/vue-json-pretty/blob/dev/README.zh-CN.md#props
现在是可以点击让数据折叠起来，怎么不让点击收起呢？感谢
