### ISSUE TITLE
Support for codepen example

### ISSUE THREAD

**Issue by mitch0667** [leezng/vue-json-pretty#86]
Hello,
I have issue building a basic example by reusing <vue-json-pretty> component with unpkg:
https://codepen.io/mitch0667/pen/KKMVQGW

> "[Vue warn]: Unknown custom element: <vue-json-pretty> - did you register the component correctly? For recursive components, make sure to provide the 'name' option.
> (found in <Root>)"

I guess my issue is that I may miss some basics of component reuse as it is my first attempt!
Any help will be much appreciated :)
Thanks!

**Comment by leezng** [comment]
The current version does not support automatic registration, so you need to manually register the component.
```js
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script src="https://unpkg.com/vue-json-pretty@1.7.0/lib/vue-json-pretty.js"></script>
<script>
  Vue.component(VueJsonPretty.default.name, VueJsonPretty.default)
</script>
```

**Comment by mitch0667** [comment]
Thanks @leezng , it is now solved!
I close the issue.
Maybe it would be nice to add it Readme (I was missing the .default when I was initially declaring the component).
