### ISSUE TITLE
Next 2.0 🚀

### ISSUE THREAD

**Issue by leezng** [leezng/vue-json-pretty#88]
The project has started the development of the next major version. List some important features here, and hope to collect some ideas and issues.

- [x] Support big data.

- [x] Support Typescript (Refactor the code using typescript or provide a .d.ts file).

- [x] Base on Vue3 (Need to discuss).

The progress can be viewed in: https://github.com/leezng/vue-json-pretty/tree/dev-next

**Comment by stepanjakl** [comment]
Vue 3 support 🙏

**Comment by leezng** [comment]
NPM next tag version is now available. Based on vue3. Welcome to try.

**Comment by ux-engineer** [comment]
This is still pinned?

Could 2.x version work with Vue 2 also? Can't upgrade yet because BSV lacks support.

**Comment by leezng** [comment]
@ux-engineer 
Now it(2.x) supports Vue3 at least. If you still use Vue2, see 1.x.
