### ISSUE TITLE
How to increase the duplicate content of the double click event

### ISSUE THREAD

**Issue by kolapapa** [leezng/vue-json-pretty#9]
I want add a event:  `v-on:dblclick.native="handleCopy"` copy the column json data 
if json like this:
```json
{
  "a": "123",
  "b": "234",
  "c": "345"
}
```
when i double click `"c": "345"` column, i will get the data of `345`

i was do like this:
```html
<vue-json-pretty
          :data="message"
          selectableType="tree"
          v-on:dblclick.native="handleCopy"
          ></vue-json-pretty>
```
```js
handleCopy(path, data) {
      console.info(data)
    },
```
but the console log is `undefined`.

是不是可以把这个click和doubleclick的 event也给用户暴露出来，定制自己的双击复制功能。

**Comment by leezng** [comment]
I am considering this feature because there is a conflict with the checkbox

**Comment by kolapapa** [comment]
加油，我看好你
