### ISSUE TITLE
TypeError with vue-cli 4.x (Vue 3.x) environment production mode

### ISSUE THREAD

**Issue by shangdeyou** [leezng/vue-json-pretty#96]
I use to develop Vue project with version 2.x and use vue-json-pretty a lot in my Vue project, it's been all good for a long time.

Recently I start the new project with Vue 3.x by vue-cli, and also install the new version 2.0.0-rc2 of vue-json-pretty.

And I got the Error since build the project and open the page (but It's work and without error since serve mode). The error message on chrome console as shown below:

![image](https://user-images.githubusercontent.com/8487840/101568214-30a46c80-3a0d-11eb-8205-5acacb8df734.png)

It was a default Hello World page, and import vue-json-pretty Component with a simple json data, the code roughly like this:

```
<template>
  <vue-json-pretty
    class="jsontree"
    :data="data">
  </vue-json-pretty>
</template>
<script>
import VueJsonPretty from 'vue-json-pretty'

export default {
  components: {
    VueJsonPretty
  },
  data () {
    return {
      data: {
        form: {
          column1: '',
          column2: '',
          column3: '',
          column4: '',
          column5: '',
        }
      }
    }
  }
}
</script>
```

#### testing project info

Project environment:

@vue/cli v4.5.9 / Vue v3.0.4

The link of source code:

https://github.com/shangdeyou/test-vue-json-pretty

**Comment by leezng** [comment]
I ran your project, but no problems were found.

Now you must upgrade to 2.0.0-rc.3.

**Comment by shangdeyou** [comment]
@leezng I tried again and update to 2.0.0-rc.3, It's ok and without error now... I don't know why... (might be npm cache??)

Anyway, thanks a lot!!!
